@startuml Register

participant Server
participant WiFiModule2

group Manufacture
    WiFiModule2 -> Server: Identity Root (IR) & Encryption Root (ER)
    
    note over WiFiModule2, Server
        * WiFiModule2_key_pair (secp-256r1)
        ** private_key_part1 = AES-CMAC(secret="Sesame2_key_pair", message=ER) 剛好 16 bytes
        ** private_key_part2 = AES-CMAC(secret=private_key_part1, message=ER)  剛好 16 bytes
        ** private_key = private_key_part1 + private_key_part2 (bytes concat, 相加總共 32 bytes)
        ** public_key=<用 ECC演算法 從 32-byte private_key 算出 64-byte public_key>
        * WiFiModule2_symm_key (ECC-ECDH):
        ** first 16 bytes of WiFiModule2 & Server ECDH shared secret
    end note
    
end

|||

group Registration
    WiFiModule2 -> 手機app **: ADV(IR)
    手機app -> WiFiModule2: BLE connect, connected, discover & enable notification
    WiFiModule2 -> 手機app: publish(WiFiModule_token)
    手機app -> Server:  HTTP_REQ(IR, WiFiModule_token, 手機app_public_key)
    
    note over Server, WiFiModule2
        **session_token** = server_token + WiFiModule_token
        **SIG1** = AES-CMAC(WiFiModule2_symm_key, 手機app_public_key + session_token)
    end note
    
    Server --> 手機app: HTTP_RESP(WiFiModule_public_key, server_token, SIG1)
    手機app -> WiFiModule2: Cmd(parsing_type=plaintext,Register,params=SIG1, 手機app_public_key, server_token)
    
    |||
    
    note over 手機app, WiFiModule2
        **ecdh_secret** = ECDH(手機app_keypair, WiFiModule2_keypair) first 16 bytes
        **reg_key** = AES-CMAC(ecdh_secret, session_token)
        **owner_key** = AES-CMAC(reg_key, "owner_key")
        **session_key** = AES-CMAC(reg_key, sessionToken)

        logged in as owner (session_key, session_token=session_token)
    end note
    
    note over Server, WiFiModule2
        **SIG2** = AES-CMAC(WiFiModule2_symm_key, owner_key + server_token)
        This 1st key is always assigned key_idx = 0 upon registration.
    end note
    
    |||
    
    WiFiModule2 --> 手機app: Rsp(plaintext, result, it_code=Register, params=SIG2)
    WiFiModule2 -> 手機app: publish(publish_login_s)
    手機app -> Server: HTTP_REQ(owner_key, server_token, SIG2)
    

end
@enduml
