name: Convert UML to PNG # Actions 名字

# 如果UML文件有变动执行脚本
on: # 触发条件
  push:
    paths:
      - '**/*.uml'
      - '**/*.puml'


jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # 选择 Java 发行版

    - name: Install Graphviz
      run: sudo apt-get install -y graphviz

    - name: Download PlantUML jar
      run: wget https://nchc.dl.sourceforge.net/project/plantuml/1.2023.7/plantuml.1.2023.7.jar

    - name: Convert UML files to PNG
      run: |
        export GRAPHVIZ_DOT=$(which dot)
        mkdir -p profile/uml/uml_output
        for uml_file in $(find . -name '*.puml' -o -name '*.uml'); do
          echo "Processing $uml_file"
          java -jar plantuml.1.2023.7.jar -o $(pwd)/profile/uml/uml_output $uml_file
        done

    - name: Upload PNG files
      uses: actions/upload-artifact@v3
      with:
        name: png-diagrams
        path: profile/uml/uml_output/*.png

    # 把生成的图片提交到仓库
    - name: Commit PNG files
      run: |
        git config --local user.email "zxc@tanguo.co"
        git config --local user.name "zxc"
        git add profile/uml/uml_output/*.png
        git commit -m "Add generated PNG files" -a || echo "No changes to commit"
        git push
